filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
    multiline.pattern: '^{'
    multiline.negate: true
    multiline.match: after

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "url-shortener-logs"

setup.kibana:
  host: "http://kibana:5601"

setup.ilm.enabled: false
setup.template.name: "url-shortener"
setup.template.pattern: "url-shortener-*"

logging.level: info
